### ISSUE TITLE
TypeNotFound in GraphQL.php line 89

### ISSUE THREAD

**Issue by eelco2k** [ttoohey/laravel-graphql-filter#1]
I'm getting this error when trying to implement the laravel-graphql-filter: 

`TypeNotFound in GraphQL.php line 89:
Type App\GraphQL\Type\Filter\Aircraft not found. `

**I have modified my Aircraft Model ( in folder: app\Models) with:** 

use Gency\Filterable\Filterable;
class Aircraft extends Model {
    use \Gency\Filterable\FilterableTrait;
    protected $filterable = [
        'naam'              => Filterable::String,
        'type'              => Filterable::String
    ];

**my FilterType class (in folder: app\GraphQL\Type\Filter) looks like this:**

namespace App\GraphQL\Type\Filter;

use Gency\GraphQLFilter\Type\FilterType;
use App\Models\Aircraft as AircraftModel;

class Aircraft extends FilterType
{
    protected $model = AircraftModel::class;
}

**and in my Query class (in folder: app\GraphQL\Query) i've added the following to my Airport.php file:**

use App\GraphQL\Type\Filter\Aircraft as AircraftFilter;
public function args()
    {
        return [
           'filter' => [
                'type' => GraphQL::type(AircraftFilter::class)
            ]
        ];
    }

Somehow the public function toType() in  of BaseType of  Folklore\GraphQL\Support is not returning a new InputObjectType... I guess....

**Comment by ttoohey** [comment]
I think you need to use the type name as argument to GraphQL::type() rather than the class path, like

```
GraphQL::type('AircraftFilter')
```

**Comment by syzygyinteractivemedia** [comment]
Thanks @ttoohey, you got me thinking and found that I did not register the facade type in graphql.php config.

So I had to add: 
 GraphQL::addType('App\GraphQL\Type\Filter\Aircraft', 'AircraftFilter');
or
in my graphql.php configfile: 

'types' => [
   'AircraftFilter'            => \App\GraphQL\Type\Filter\Aircraft::class
]

I works now!
